name: Build KiTTY (Windows 32/64bit)

on:
  push:
    tags:
      - v*
  workflow_dispatch:  # Allow manual run via GitHub UI

env:
  VERSION: 0.76b

jobs:
  build32:
    name: Windows 32-bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build (32-bit)
        run: |
          mkdir -p builds
          docker run --rm -i \
            -v ${{ github.workspace }}/builds:/builds \
            -v ${{ github.workspace }}:/sources \
            cyd01/cross-gcc \
            "cd ${VERSION}_My_PuTTY/windows ; make -f MAKEFILE.MINGW cross ; cp *.exe /builds/"
      - uses: actions/upload-artifact@v4
        with:
          name: kitty-32bit
          path: builds/

  build64:
    name: Windows 64-bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build (64-bit)
        run: |
          mkdir -p builds
          docker run --rm -i \
            -v ${{ github.workspace }}/builds:/builds \
            -v ${{ github.workspace }}:/sources \
            cyd01/cross-gcc \
            "cd ${VERSION}_My_PuTTY/windows ; make -f MAKEFILE.MINGW cross64 ; cp *.exe /builds/"
      - uses: actions/upload-artifact@v4
        with:
          name: kitty-64bit
          path: builds/
