name: Build KiTTY

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [32bit, 64bit]
    name: Build KiTTY (${{ matrix.target }})
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create builds directory
        run: mkdir -p builds
        
      - name: Build KiTTY
        run: |
          docker run --rm -v $(pwd)/builds:/builds \
            -e USR_UID=$(id -u) -e USR_GID=$(id -g) \
            cyd01/cross-gcc \
            "git clone https://github.com/cyd01/KiTTY.git ; \
             cd KiTTY/0.76b_My_PuTTY/windows ; \
             make -f MAKEFILE.MINGW cross$([[ '${{ matrix.target }}' == '64bit' ]] && echo '64') ; \
             cd /builds ; ls -l"
             
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kitty-${{ matrix.target }}
          path: builds/
