name: Build KiTTY (Windows 32/64bit)

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  VERSION: 0.76b

jobs:
  build32:
    name: Windows 32-bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build (32-bit, cross-docker)
        run: |
          mkdir -p builds 2>/dev/null || rm -f builds/*.exe
          docker run --rm -it \
            -v ${{ github.workspace }}/builds:/builds \
            -e USR_UID=$(id -u) \
            -e USR_GID=$(id -g) \
            cyd01/cross-gcc \
            "git clone https://github.com/cyd01/KiTTY.git ; cd KiTTY/0.76b_My_PuTTY/windows ; make -f MAKEFILE.MINGW cross ; cd /builds ; ls -l"
      - uses: actions/upload-artifact@v4
        with:
          name: kitty-32bit
          path: builds/

  build64:
    name: Windows 64-bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build (64-bit, cross-docker)
        run: |
          mkdir -p builds 2>/dev/null || rm -f builds/*.exe
          docker run --rm -it \
            -v ${{ github.workspace }}/builds:/builds \
            -e USR_UID=$(id -u) \
            -e USR_GID=$(id -g) \
            cyd01/cross-gcc \
            "git clone https://github.com/cyd01/KiTTY.git ; cd KiTTY/0.76b_My_PuTTY/windows ; make -f MAKEFILE.MINGW cross64 ; cd /builds ; ls -l"
      - uses: actions/upload-artifact@v4
        with:
          name: kitty-64bit
          path: builds/
